In [1]:
import pandas as pd
import pandera as pa

Importação caso o separador seja outra coisa que não a virgula
data_frame=pd.read_csv("ocorrencia_2010_2020.csv",sep=";")
data_frame

Aqui ele vai importar tudo, mas dará problema com os objetos do tipo data, ou tipos espécificos, eu foi tipando as colunas...
df=pd.read_csv("ocorrencia_2010_2020.csv")
df

In [2]:
#sei que não converteu a data por questão dela já vir no formato dia, mes ano
df=pd.read_csv("ocorrencia_2010_2020.csv",sep=',',parse_dates=['ocorrencia_dia'])
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,03/01/2010,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,03/01/2010,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,03/01/2010,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,04/01/2010,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,05/01/2010,19:25:00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,29/12/2020,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,****,30/12/2020,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,30/12/2020,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,31/12/2020,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,-43,37,RJ,BRASIL,SBJR,NÃO,1,NÃO

In [3]:
df.dtypes

codigo_ocorrencia            int64
codigo_ocorrencia2           int64
ocorrencia_classificacao    object
ocorrencia_cidade           object
ocorrencia_uf               object
ocorrencia_aerodromo        object
ocorrencia_dia              object
ocorrencia_hora             object
total_recomendacoes         object
Unnamed: 9                  object
Unnamed: 10                 object
dtype: object

df.ocorrencia_dia.dt.month

é pra dar erro pois ele não reconhece como data, por isso o comentário na importação

In [4]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,03/01/2010,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,03/01/2010,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,03/01/2010,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,04/01/2010,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,05/01/2010,19:25:00,0,NaN,NaN
5,39807,39807,INCIDENTE,SALVADOR,BA,****,06/01/2010,17:53:00,0,NaN,NaN
6,40215,40215,INCIDENTE,COARI,AM,SBUY,07/01/2010,18:40:00,0,NaN,NaN
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,****,09/01/2010,12:30:00,3,NaN,NaN
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,10/01/2010,23:15:00,2,NaN,NaN
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,****,10/01/2010,20:00:00,0,NaN,NaN

In [5]:
df.tail(15)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
5737,79748,79748,ACIDENTE,SANTANA DO LIVRAMENTO,RS,####,23/12/2020,13:30:00,0,NaN,NaN
5738,79787,79787,INCIDENTE,FORTALEZA,CE,SBFZ,23/12/2020,18:30:00,0,NaN,NaN
5739,79749,79749,ACIDENTE,MARITUBA,PA,****,26/12/2020,12:05:00,0,NaN,NaN
5740,79751,79751,ACIDENTE,PRESIDENTE CASTELO BRANCO,PR,SSXO,27/12/2020,12:30:00,0,NaN,NaN
5741,79754,79754,INCIDENTE GRAVE,NOVA MARINGÁ,MT,****,28/12/2020,13:00:00,0,NaN,NaN
5742,79800,79800,INCIDENTE,SÃO PAULO,SP,SBMT,28/12/2020,10:15:00,0,NaN,NaN
5743,79824,79824,ACIDENTE,RIO PARANAÍBA,MG,SNRP,28/12/2020,17:00:00,0,NaN,NaN
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,****,29/12/2020,12:00:00,0,NaN,NaN
5745,79755,79755,ACIDENTE,MATO RICO,PR,****,29/12/2020,10:30:00,0,NaN,NaN
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,29/12/2020,18:30:00,0,NaN,NaN
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,29/12/2020,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,****,30/12/2020,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,30/12/2020,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,31/12/2020,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,-43,37,RJ,BRASIL,SBJR,NÃO,1,NÃO

In [6]:
schema=pa.DataFrameSchema(
    columns={
        "codigo_ocorrencia":pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "ocorrencia_cidade":pa.Column(pa.String),
#"ocorrencia_uf":pa.Column(pa.String,pa.Check.str_length(2,2)),
        "ocorrencia_uf":pa.Column(pa.String),
        "ocorrencia_aerodromo":pa.Column(pa.String),
#"ocorrencia_dia":pa.Column(pa.DateTime), era pra ser isso né, mas tive problemas com date
        "ocorrencia_dia":pa.Column(pa.String),
        "ocorrencia_hora":pa.Column(pa.String, nullable=True),
        "total_recomendacoes":pa.Column(pa.String, nullable=True)      
#"total_recomendacoes":pa.Column(pa.String, required=False) pode ser que um dado específico não tenha esta coluna, aqui ele dispensa ela
        
    }
)

In [7]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,03/01/2010,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,03/01/2010,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,03/01/2010,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,04/01/2010,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,05/01/2010,19:25:00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,29/12/2020,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,****,30/12/2020,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,30/12/2020,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,31/12/2020,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,-43,37,RJ,BRASIL,SBJR,NÃO,1,NÃO